### ISSUE TITLE
TemplateManifest add resolving tokens from secrets file

### ISSUE THREAD

**Issue by RomaRudyak** [dansiegel/Mobile.BuildTools#42] opened 2018-07-24 10:34 UTC
I have project where I am using google auth.
I use secrets.json for path them to my project:
```json
{
    "ClientId" : "[Id from Google console]"
}
```
on iOS there one restriction that I need add it to Info.plist:
```xml
        <key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLTypes</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.$$ClientId$$</string>
			</array>
		</dict>
	</array>
```

Actual Result:
TemplateManifest target use only Environment variables for resolving tokens

Expected:
TemplateManifest target will use secrets.json values for resolving tokens as if secrets.json not exist it will be created by BuildHostSecrets on build server

**Comment by dansiegel** [comment] 2018-07-26 16:08
closing as a duplicate of #40

**Closed by dansiegel** 2018-07-26 16:08 UTC
