### ISSUE TITLE
VSTS secrets not getting generated

### ISSUE THREAD

**Issue by NicoVermeir** [dansiegel/Mobile.BuildTools#48] opened 2018-08-21 11:28 UTC
# Description
I've added the buildtools nuget package to a Xamarin Forms 3 project (.net standard, iOS, Android, UWP heads)

I added a secret.json file with the endpoint of our develop api, in the VSTS CI build for our iOS project I added a Process variable with the name Secret_ApiEndpoint. 
![image](https://user-images.githubusercontent.com/3177418/44398783-6c1d8300-a545-11e8-9c1e-25e5d7033904.png)

on build the Secret_ApiEndpoint gets ignore, but the P12password that is used for the apple provisioning task gets turned into an entry

from the output:
`  Generating secrets.json for Secret_
  {
    "P12PASSWORD": "*****"
  }
Secrets:
  
  OutputPath: /Users/vsts/agent/2.138.6/work/1/s/<Redacted>/<Redacted>/Helpers
  // ------------------------------------------------------------------------------
  //  <autogenerated>
  //      This code was generated by Mobile.BuildTools. For more information or to
  //      file an issue please see https://github.com/dansiegel/Mobile.BuildTools
  //
  //      Changes to this file may cause incorrect behavior and will be lost when 
  //      the code is regenerated. 
  //
  //      NOTE: This file should be excluded from source control.
  //  </autogenerated>
  // ------------------------------------------------------------------------------
  
  namespace Helpers
  {
      internal static class Secrets
      {
          internal const string P12PASSWORD = "*****";
      }
  }
  
  Writing Secrets Class to: 'obj/Release/netstandard2.0/Secrets.cs'`

## Reproduction Steps

1. Go to VSTS
2. Setup a CI pipeline Xamarin iOS
3. Add a variable that should end up as a secret

## Expected Behavior
The variable to get picked up by the secret generating task

## Actual Behavior
Variable gets ignored

## Environment
- VSTS, Hosted macOS Preview
- BuildTools Version: 1.4.0.638
- IDE Version: [1.x.x]
- Build Target Framework: Xamarin Forms 3.1 with .net standard 2.0

**Comment by dansiegel** [comment] 2018-08-21 13:33
Closing as a duplicate of #47

**Closed by dansiegel** 2018-08-21 13:33 UTC
